# We do not currently run WebGPU tests on ARM Macs in CI (bug 1889642). Until
# we do, force `dom.webgpu.enabled` on Mac so these tests run on Intel Macs in
# CI, even though WebGPU is not normally enabled on Intel Macs in beta or
# release builds (bug 2004105).
prefs:
  if os == "mac": [dom.webgpu.service-workers.enabled:true, dom.webgpu.testing.assert-hardware-adapter:true, media.rvfc.enabled:true, privacy.baselineFingerprintingProtection:false, dom.webgpu.enabled:true]
  if os == "win": [dom.webgpu.service-workers.enabled:true, dom.webgpu.testing.assert-hardware-adapter:true, media.rvfc.enabled:true, privacy.baselineFingerprintingProtection:false]
  [dom.webgpu.service-workers.enabled:true, media.rvfc.enabled:true, privacy.baselineFingerprintingProtection:false]
tags: [webgpu]
disabled:
  if os != "win" and os != "mac" and release_or_beta: https://mozilla-hub.atlassian.net/browse/FFXP-223
